#!/bin/bash
# Quick setup guide for Swasya AI

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 Swasya AI - Quick Setup Guide"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "📋 Step 1: Get API Keys"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend requires 2 API keys:"
echo ""
echo "1️⃣  GEMINI_API_KEY"
echo "   Get from: https://ai.google.dev/"
echo "   1. Go to Google AI Studio"
echo "   2. Create a new API key"
echo "   3. Copy the key"
echo ""
echo "2️⃣  GROQ_API_KEY"
echo "   Get from: https://groq.com/"
echo "   1. Sign up / Login"
echo "   2. Get your API key from settings"
echo "   3. Copy the key"
echo ""

echo "📝 Step 2: Update Environment Files"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend (.env):"
echo "  File: backend/simple_backend/.env"
echo ""
echo "  Add your keys:"
echo "  export GEMINI_API_KEY=sk-xxxxx......"
echo "  export GROQ_API_KEY=xxxxx......"
echo ""
echo "Frontend (.env):"
echo "  File: client/.env"
echo ""
echo "  Pre-configured with:"
echo "  export VITE_API_BASE_URL=http://172.22.171.18:8000"
echo "  export VITE_NODE_ENV=development"
echo ""

echo "🚀 Step 3: Start Development"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run:"
echo "  mprocs"
echo ""
echo "This will start:"
echo "  ✅ Backend  — FastAPI on http://172.22.171.18:8000"
echo "  ✅ Frontend — Vite on http://localhost:5173"
echo ""

echo "🎮 mprocs Controls"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  q    = Quit"
echo "  k/j  = Navigate"
echo "  s    = Start process"
echo "  x    = Stop process"
echo "  r    = Restart"
echo "  <C-a> = Toggle focus"
echo ""

echo "═══════════════════════════════════════════════════════════════"
